apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-test
spec:
  selector:
    matchLabels:
      for_app: pv-volume-test
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  volumeName: pv-volume-test