version: "3"

volumes:
  jupyter-notebooks:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tho78s/development/ANSTO/areaDetectorZMQ-docker/notebooks
  test:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tho78s/development/ANSTO/areaDetectorZMQ-docker/test   

services:
  ophyd-bluesky:
    image: dpi/ophyd-bluesky:latest
    container_name: ophyd-bluesky
    volumes:
      - jupyter-notebooks:/opt/notebooks
    ports: 
      - 8888:8888
    command: "jupyter lab --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token=''"
    depends_on: 
      - "area-detector-zmq"
    tty: true

  frame-grabber:
    image: dpi/zmq-python-docker:3.6
    container_name: frame-grabber
    environment:      
      - ZMQ_SUBSCRIBER_ADDRESS=tcp://area-detector-zmq:5559
    volumes:
      - test:/app
    command: "python frame-grabber.py"  
    depends_on: 
      - "area-detector-zmq"       
    tty: true

  #remote-dispatcher:
  #  image: dpi/ophyd-bluesky:latest
  #  environment:
  #    - REMOTE_DISPATCHER_PUB_PORT=5577
  #    - REMOTE_DISPATCHER_SUB_PORT=5578
  #  command: bash -c "./remote_dispatcher_test.sh"
  #  volumes:
  #    - test:/tmp      
  #  depends_on: 
  #    - "ophyd-bluesky"
  #  tty: true      
    
  area-detector-zmq:
    image: dpi/area-detector-zmq
    container_name: area-detector-zmq
    build:
      context: .
      args: 
        - BASE_IMAGE=prjemian/synapps-6.2
        - AREA_DETECTOR_REPO=https://github.com/areaDetector/areaDetector.git
        - AREA_DETECTOR_REPO_TAG=master
        - ZMQ_REPO=https://github.com/darrent1974/ADZMQ.git
        - ZMQ_TAG=master  
    environment:
      - ZMQ_PRODUCER_ADDRESS="tcp://*:5559 PUB"  
      - ADZMQ_QUEUE_SIZE=50
      - ADZMQ_BLOCKING_CALLBACKS=1
      - SIMDETECTOR_IOC_MAX_XSIZE=2048
      - SIMDETECTOR_IOC_MAX_YSIZE=2048
      - SIMDETECTOR_IOC_DATATYPE=3 # uint16
    ports: 
      - 5559:5559 
    cap_add:
       - SYS_PTRACE
    security_opt:
       - seccomp:unconfined               
    command: bash -c "/opt/runADSimDetector.sh && tail -f /dev/null"
  #  volumes:
  #    - ./autosave:/opt/iocSimDetector/autosave
  #    #- ./ADZMQ:/opt/synApps/support/areaDetector-master/ADZMQ
    tty: true 
     