apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: zmq-forwarder
  name: zmq-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zmq-forwarder
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.kompose.service: zmq-forwarder
    spec:
      containers:
        - args:
            - python
            - forwarder-device.py      
          env:
            - name: ZMQ_PRODUCER_DEVICE_ADDRESS
              value: tcp://*:5559
            - name: ZMQ_WORKER_DEVICE_ADDRESS
              value: tcp://*:5560
          image: dpi/zmq-python-docker:3.6
          imagePullPolicy: Never
          name: zmq-forwarder
          ports:
            - containerPort: 5559
            - containerPort: 5560
          resources: {} 
          tty: true
          volumeMounts:
            - name: persistent-storage-zmq-forwarder
              mountPath: /app
      restartPolicy: Always
      volumes:
      - name: persistent-storage-zmq-forwarder
        persistentVolumeClaim:
          claimName: pv-claim-test
status: {}
