apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: area-detector-zmq
  name: area-detector-zmq
spec:
  ports:
    - name: "5559"
      port: 5559
      targetPort: 5559
  selector:
    io.kompose.service: area-detector-zmq
  type: NodePort
status:
  loadBalancer: {}
