apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ophyd-bluesky
  name: ophyd-bluesky
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: ophyd-bluesky
  type: NodePort
status:
  loadBalancer: {}
